<?php

// Status codes
CondDefine('STATUS_OK', 0);
CondDefine('STATUS_SQL_ERROR', 1);
CondDefine('STATUS_INVALID_ACTION', 2);
CondDefine('STATUS_USERNAME_IS_ALREADY_EXISTS', 3);
CondDefine('STATUS_EMAIL_IS_ALREADY_EXISTS', 4);

// status message language keys
CondDefine('STATUS', array(
    STATUS_OK => 'STATUS_OK',
    STATUS_SQL_ERROR => 'STATUS_SQL_ERROR',
    STATUS_INVALID_ACTION => 'STATUS_INVALID_ACTION',
    STATUS_USERNAME_IS_ALREADY_EXISTS => 'STATUS_USERNAME_IS_ALREADY_EXISTS',
    STATUS_EMAIL_IS_ALREADY_EXISTS => 'STATUS_EMAIL_IS_ALREADY_EXISTS'
));